# -*- coding: utf-8 -*-
"""elnino.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MUx1xjl2Kkh27okNNN3pIH_nk-0tKm50
"""

import pandas as pd

data = pd.read_csv('/content/elnino.csv')
data.head()

"""Cleaning Data"""

data = data.dropna()
data = data.drop_duplicates()
data.head()
data.shape

data.info()

print(data.columns)

"""Rata Rata Temperatur udara"""

data[' Air Temp'] = pd.to_numeric(data[' Air Temp'], errors='coerce')
rata_rata = data[' Air Temp'].mean()
print(' Air Temp (mean):', rata_rata)

"""median Temperatur udara"""

rata_rata = data[' Air Temp'].median()
print(' Air Temp (median):',rata_rata)

"""Modus Temperatur udara"""

modus = data[' Air Temp'].mode()
print('Air Temp (modus):', modus)

"""Simpangan Rata Rata Temperatur udara"""

deviasi_absolut = abs(data[' Air Temp'] - rata_rata)

simpangan_rata_rata = deviasi_absolut.mean()

print('Simpangan Rata-rata Air Temp:', simpangan_rata_rata)

"""Diagram Temperatur udara"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8, 5))
sns.barplot(x=' Day', y=' Air Temp', data=data, palette='viridis')
plt.xlabel("Day")
plt.ylabel("Air Temp")
plt.title("Rata-rata Suhu di Berbagai Kota")
plt.show()